blank_issues_enabled: false
contact_links:
  - name: Website
    url: http://toxicity-protection.xyz/
    about: Check out our Website for more info.
  - name: Discord
    url: https://discord.gg/4ja5SmyYs5
    about: Join our Discord Server to chat.
